### ISSUE TITLE
Anyways to change the mouse move speed?

### ISSUE THREAD

**Issue by Sl1ckR1ck** [FlaUI/FlaUI#194]
Hi again,

i already wrote my own mouse move method to show a smooth mouse move.
The idea is that my coded UI tests will also be used to automate some video tutorials (thus the need to record the mouse movement).

I see that the control.Click method now have a 'mouveMouse' variable to it which works nice, but a little too fast.

Is there a way to specify the speed of this mouse move?

Thanks :)

**Comment by Roemer** [comment]
Thanks. I actually moved my implementation to your logic and with 3.0.0, it will also expose the static properties `MovePixelsPerMillisecond` and `MovePixelsPerStep` so this can be set globally.

**Comment by zastrowm** [comment]
It looks like the properties are exposed, but not settable:

https://github.com/FlaUI/FlaUI/blob/f70ab2392c65fe68527b7db5c9bc12306c23b49b/src/FlaUI.Core/Input/Mouse.cs#L63

Is that intentional?

I have the opposite problem where clicking is too slow, so I'd like to increase the speed, but noticed that it's readonly.

**Comment by Roemer** [comment]
Right, I made them settable now (https://github.com/FlaUI/FlaUI/commit/c1bc7db0fba6d671c7a179bb9811d6c70c4f4e8a)

**Comment by Roemer** [comment]
A new release is out (3.1.0) and you should be able to set them now.
