### ISSUE TITLE
Visibility parameter of WPF control not visible with UI Automation?

### ISSUE THREAD

**Issue by kevinheyvaert** [FlaUI/FlaUI#210]
I started writing test for a WPF application with FlaUI. Now I want to get the Visibility value of a couple of buttons. 

These buttons are located on the same position in the WPF window. The first is a start button which will start a measurement. When clicked, the measurement button is replaced with a stop button. The visibility of these buttons are set in the code behind of the xaml and needs to be checked/verified.

With FlaUI I only get IsEnabled boolean and OffScreen boolean. But when using the Offscreen parameter, this boolean is not set or is set to the correct value for a couple of seconds but is changed again while the measurement is still running. 

I also tried other ways, like looking for a clickable point of the not visible button. But these were not effective.

Can this be done without extending the button class with an AutomationPeer and exposing a ValuePattern? I googled a bit but cannot find an (decent) answer. Hopefully someone can help.

**Comment by dojo90** [comment]
Did you find a solution? I also want to know how to get the visibility

**Comment by kevinheyvaert** [comment]
@dojo90  did you find a solution? In this link of [Microsoft Docs](https://docs.microsoft.com/en-us/dotnet/api/system.windows.automation.automationelement.automationelementinformation.isoffscreen?view=netframework-4.7.2), there is no visibility parameter on an AutomationElement object. So i think you have to do it with Value pattern.

**Comment by dojo90** [comment]
Currently I have not pursued the problem further. 😬

**Comment by Roemer** [comment]
I actually implemented a custom property that exposes the `Visibility` of a WPF control. I found out that a control that is `Hidden` or `Collapsed` is actually removed completely from the UIA-Tree so you do not see that item anymore via FlaUI/UIA. So it does not make sense to expose that property at all :)

**Comment by maxinfet** [comment]
@Roemer I am surprised to hear that Hidden or Collapsed would remove from the tree. In my experience with WPF applications controls that are not shown but are on the form would usually show a rectangle in the top left hand corner and no bounding rectangle property. Here is an example from Visual Studio but I run into these all the time at work.

![image](https://user-images.githubusercontent.com/3291391/88417334-c4073900-cdaf-11ea-8ecc-5eeb898a5a3f.png)

You can see this by opening VS without opening a solution and digging through the solution explorer for the Search Control that would normally be there. The reason I bring this up is because this entire time I thought collapsed and hidden controls were in the tree like what is shown in my  screen shot so I thought our application was doing it correctly. If this is incorrect behavior that certainly changes some of the investigations I have done in the past. :smile:

**Comment by Roemer** [comment]
Hey Max
Nice to hear from you. Interesting, I just did a new WPF project with a Label and when it was anything else than `Visible`, it did not show in UIA. Maybe it is something Label-related. Anyway, I am currently working on support for custom properties at least for WPF (already working) and for custom patterns, then it's a breeze to get additional properties to UIA ;)

**Comment by Josch600** [comment]
Is there meanwhile a solution for the problem? I have a textblock within my wpf application, which is set to Visibility.Collapsed under certain condition. FlaUI finds it always regardless if visible or not, I can always check the contained text, but I find no way to check if it is visible or not. :-(
