### ISSUE TITLE
Does FlaUI supports   Framework Type is 'QT '

### ISSUE THREAD

**Issue by tusarranajan** [FlaUI/FlaUI#297]
Does FlaUI supports  if Framework Type is 'QT '

**Comment by Roemer** [comment]
In general that should work yes. For example the `Telegram` application correctly reports `FrameworkId` as `Qt`:
![image](https://user-images.githubusercontent.com/393641/71821495-94eadd80-3092-11ea-831d-a157f9353138.png)

**Comment by Roemer** [comment]
The next version will also add this as known framework type (see 7349f6165deb32e30b767903415bf8ee7d843c25)

**Comment by Roemer** [comment]
This is now released.

**Comment by JobaDiniz** [comment]
> The next version will also add this as known framework type (see [7349f61](https://github.com/FlaUI/FlaUI/commit/7349f6165deb32e30b767903415bf8ee7d843c25))

Is this the only requirement to support `Qt`?
Because there are a lot of places in the code that verifies the `FrameworkType` and in `else` conditions just throws `NotSupportedException` or assumes `WPF` or other framework type, examples

- https://github.com/FlaUI/FlaUI/blob/master/src/FlaUI.Core/AutomationElements/Scrolling/HorizontalScrollBar.cs#L22
- https://github.com/FlaUI/FlaUI/blob/master/src/FlaUI.Core/AutomationElements/Calendar.cs#L61
- https://github.com/FlaUI/FlaUI/blob/master/src/FlaUI.Core/AutomationElements/ComboBox.cs#L196
