### ISSUE TITLE
Auto filter Row

### ISSUE THREAD

**Issue by cpattynue** [FlaUI/FlaUI#347]
Hi,
I'm new in FLAUI.
i'm creating an automated UI project and I have a problem with a grid and the Auto filter Row.
If I run the application and search the Grid definition, I saw the Next:
![image](https://user-images.githubusercontent.com/4432526/82829699-8488a300-9e79-11ea-879d-134c0db350d3.png)

My Grid have 3 rows, (header, Row0 and Row1)
But if I see my grid in the application I have 4 rows
![image](https://user-images.githubusercontent.com/4432526/82829937-17c1d880-9e7a-11ea-942e-5bc1168757f4.png)
 (Header, **FILTER ROW**, Row0, Row1)

I can't see the Filter row in the inspect tool until i clicked on it in the applciation:
![image](https://user-images.githubusercontent.com/4432526/82829823-ce718900-9e79-11ea-94cc-de4030743d87.png)

So... How can I access to this filter row (I need to filter for an specific text) if the object do not exist so i can not click on it...

**Comment by Roemer** [comment]
Depending on your grid-control it might be that the filter row is not visible (no control at all) until it is activated (clicked). If that is the case you could try to  just click 10 pixels under the header row in order to activate the filter control, then get the filter control as edit (probably with a small Retry or at least delay) and edit the value in it.
