### ISSUE TITLE
VB6 modal windows not accessible via FlaUI

### ISSUE THREAD

**Issue by josef-marec** [FlaUI/FlaUI#385]
hello,

i'm automating ancient vb6 app and all modal windows are "invisible", i.e. ModalWindows property is always empty and FlaUInspect does not show such windows in UIA tree

however, in hover mode highlighting works for elements inside modal window; in microsofts accesibility insights tool is modal window displayed, please see screenshots

my automation code uses UIA3, FlaUInspect behaves independently on UIA version

FlaUInspect UIA2:

![uia2](https://user-images.githubusercontent.com/56034889/101163560-0f6e0580-3634-11eb-8687-a507923e3cc4.png)

FlaUInspect UIA3:

![uia3](https://user-images.githubusercontent.com/56034889/101163617-257bc600-3634-11eb-83d9-7b9274393f88.png)

accessibilityinsights.io:

![ai](https://user-images.githubusercontent.com/56034889/101163688-417f6780-3634-11eb-914e-80e8d91af3dc.png)

am i missing something? in different issue about modals, there is screenshot showing modal window in the tree ... https://github.com/FlaUI/FlaUI/issues/52

if it helps - window is opened this way: https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-basic-6/aa244181(v=vs.60)

thaks for your time,
jos

**Comment by maxinfet** [comment]
I would wager that when the window is created Microsoft Active Accessibility is not sending the [WM_GETOBJECT ](https://docs.microsoft.com/en-us/windows/win32/winauto/wm-getobject) message. Then when you hover over it with FlaUIInspect or Accessibility Insights it causes one of the [AccessibleObjectFromX ](https://docs.microsoft.com/en-us/windows/win32/winauto/how-wm-getobject-works)functions to get called which forces Microsoft Active Accessibility to send that message. You should use something like Spy++ to look at the windows messages that are sent when that window opens and see if the WM_GETOBJECT is not sent until you hover over the window with one of the tools.

**Comment by josef-marec** [comment]
not sure if i follow

if hovering forces the window to send WM_GETOBJECT, then it whould show up in the tree, right? but that is not happening

i've searched for window "Edit User" across whole tree, running FlaUInspect as admin, without results; our application heavily uses COM+, so ownership of window could definitely be the root of our trouble

i'll consult that Spy++ with a colleague later, but our first shot will be opening the window modeless and/or specify the owner

there is one more strange thing - screenshot in https://github.com/FlaUI/FlaUI/issues/52 shows, that LocalizedControlType is "modal", but for our application Accessibility Insights says, that the modal window LocalizedControlType is "window", so it feels to me like FlaUI ignores that window when searching child ModalWindows (because its type is not "modal"), and it ignores that window when seaching for other children (WindowPattern.IsModal = True)

thanks!
jos

**Comment by maxinfet** [comment]
> not sure if i follow
> 
> if hovering forces the window to send WM_GETOBJECT, then it whould show up in the tree, right? but that is not happening
> 
> i've searched for window "Edit User" across whole tree, running FlaUInspect as admin, without results; our application heavily uses COM+, so ownership of window could definitely be the root of our trouble
> 
> i'll consult that Spy++ with a colleague later, but our first shot will be opening the window modeless and/or specify the owner
> 
> there is one more strange thing - screenshot in #52 shows, that LocalizedControlType is "modal", but for our application Accessibility Insights says, that the modal window LocalizedControlType is "window", so it feels to me like FlaUI ignores that window when searching child ModalWindows (because its type is not "modal"), and it ignores that window when seaching for other children (WindowPattern.IsModal = True)
> 
> thanks!
> jos

So the window doesn't send WM_GETOBJECT, Windows sends that. So what I meant was that hovering over a control on the window can cause Windows to send the message to the window. There's also other applications that will cause this message to be sent. As of a Windows patch roughly 1 year ago they updated rdpclip to force full UI automation to be turned on to fix a WPF bug when partial UI automation is on. Our company had some issues with this because generating automation peers for some of our grids was not cheap and I talked to a Microsoft representative about it which is the only reason I'm aware of it. I think you have the right approach though to check the ownership of the window first then if you still are experiencing issues after assigning the correct owner then using spy++ to watch Windows messages and see what is being sent and when.

I do have another question though are you handling Windows messages yourself or are you letting VB6 handle Windows messages? As far as I know you could hook into the windows pump and VB6 and handle the messages yourself but I've only seen it done in a couple of rare cases in our legacy application. I would be curious if there's some fall through condition when handling Windows messages if you are handling them.

**Comment by josef-marec** [comment]
similar newer issues:

https://github.com/FlaUI/FlaUI/issues/453

https://github.com/FlaUI/FlaUI/issues/458

i did not really dig into window messaging, our task is to transpile VB6 code into VB.NET and then modernize the application, so we need some automated tests to move forward and lack of automation ids is not a real problem

simple solution for me is this: modal window gets immediately focused, so i just use UIA3Automation.FocusedElement and by traversing via AutomationElement.Parent i get that modal window

all FlaUInspect-like tools have same behavior - they don't display my modal window, except for one, which displays it in CTRL+hover mode - VisulUIAVerify, part of windows SDK

thanks @maxinfet
