### ISSUE TITLE
How to evaluate if a window is in the foreground?

### ISSUE THREAD

**Issue by Jteve-Sobs** [FlaUI/FlaUI#497]
I want to find out if a window is opened in the foreground.

I tried the following:
`element.AsWindow().Patterns.Window.Pattern.IsTopmost;`
However this always reports false.

I can set a window into the foreground with the following code:
`element.AsWindow().SetForeground();`
But I have found no way to check this.

How would I do this?

**Comment by Jteve-Sobs** [comment]
After a few tests the property did not always work so I did not open a pull request on this.
Using the code above did sometimes work, so you can try this for a project.

**Comment by hugener** [comment]
I was looking for a way to do this as well and think I would a way.

I noticed in Automation Spy, that a Window which is not in focus, doesn't have a clickable point, so the presence of clickable point could be used to determine if the Window should be considered in foreground.
I tried this with FlaUI, but noticed that the TryGetClickablePoint, will go lengths to return a point, rather than staying true to the raw UI automation. From the code below I'm suspecting that it's creating the point from the bounding box:
https://github.com/FlaUI/FlaUI/blob/f1cd3a31ca17c4fb95f1050dda5b2e7908e194ae/src/FlaUI.UIA3/UIA3FrameworkAutomationElement.cs#L147-L176

This not necessarily wrong, so maybe a boolean property name IsInFocus, that returns true if the raw TryGetClickablePoint also return true could be a solution?
