### ISSUE TITLE
Finding Element based off of Partial text? (XPath or something else maybe)

### ISSUE THREAD

**Issue by Tree55Topz** [FlaUI/FlaUI#664]
Hello - am trying to test out FlaUI to see if it might be worth the time to convert from a WinAppDriver automation framework. One downside of our application is that it often uses large grids lacking in automationIds, or filters that dont work with certain characters so sometimes we have to resort to using XPath for element selection.

I am not seeing any clear examples of how this is best done in FlaUI. I have tried something like this in a method but I get an ObjectReference error every time, even when not using contains and using full text instead.

`targetSelection = container.FindFirstByXPath($"//*[contains(@Name, '{value}')]");`

Is there any examples on how best to use XPath or partial text with Name, AutomationId or ClassName in FlaUI?

**Comment by louislefevre** [comment]
If you want to match partial text against name/ID/class, you can try utilising the `PropertyConditionFlags` enum. For example:
```c#
PropertyCondition condition = mainWindow.ConditionFactory.ByAutomationId("myPartialAutomationId", PropertyConditionFlags.MatchSubstring);
AutomationElement? foundElement = mainWindow.FindFirstDescendant(condition);
```

Otherwise, if you have elements that have no unique ID, name, class, etc, you can instead search by control type and then use indexes to get the correct element. Lets say you have three grids, none of which have an ID, then you can retrieve all of the grids and select them based on their index. The only downside to this is that if the UI changes (e.g. a fourth grid is added inbetween the second and third), then you'll need to update the code to fix the indexes.
```c#
PropertyCondition condition = mainWindow.ConditionFactory.ByControlType(ControlType.DataGrid);
AutomationElement[]? gridElements = mainWindow.FindAllDescendants(condition);

AutomationElement firstGrid = gridElements.ElementAt(0).AsGrid();
AutomationElement secondGrid = gridElements.ElementAt(1).AsGrid();
AutomationElement thirdGrid = gridElements.ElementAt(2).AsGrid();
```

**Comment by Tree55Topz** [comment]
@louislefevre that suggestion worked great! very cool, nice to not have to resort to XPath for such calls. Thanks!
